[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
lisk_sepolia = "https://rpc.sepolia-api.lisk.com"
lisk_mainnet = "https://rpc.api.lisk.com"

[etherscan]
lisk_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://sepolia-blockscout.lisk.com/api" }
lisk_mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://blockscout.lisk.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
